#!/bin/zsh

set -e

file=$1
name=${file:t}
date="$(date +'%F')"
key=$date'/'"$(mkpw)"'/'"$name"
target='s3://ellbur-misc-stuff/'"$key"
aws s3 cp $file $target
aws s3api put-object-acl --bucket ellbur-misc-stuff --key $key --acl public-read
key_with_pluses="$(add-pluses $key)"
echo 'https://d35yeutfwbbcir.cloudfront.net/'"$key_with_pluses"

