#!/bin/zsh

clear > /etc/issue
echo -en "\e]P0232323" >> /etc/issue
echo -en "\e]P82B2B2B" >> /etc/issue
echo -en "\e]P1D75F5F" >> /etc/issue
echo -en "\e]P9E33636" >> /etc/issue
echo -en "\e]P287AF5F" >> /etc/issue
echo -en "\e]PA98E34D" >> /etc/issue
echo -en "\e]P3D7AF87" >> /etc/issue
echo -en "\e]PBFFD75F" >> /etc/issue
echo -en "\e]P48787AF" >> /etc/issue
echo -en "\e]PC7373C9" >> /etc/issue
echo -en "\e]P5BD53A5" >> /etc/issue
echo -en "\e]PDD633B2" >> /etc/issue
echo -en "\e]P65FAFAF" >> /etc/issue
echo -en "\e]PE44C9C9" >> /etc/issue
echo -en "\e]P7E5E5E5" >> /etc/issue
echo -en "\e]PFFFFFFF" >> /etc/issue
clear >> /etc/issue

echo '' >> /etc/issue
echo '\s' >> /etc/issue
echo '\l' >> /etc/issue
echo '\n' >> /etc/issue
echo '\r' >> /etc/issue
echo '\v' >> /etc/issue

