#!/bin/zsh

dconf write /theme "'dark'"
dconf write /org/gnome/desktop/interface/gtk-theme "'Orchis-Dark'" 

/bin/rm -f ~/.gtkrc-2.0
ln -s .gtkrc-2.0-dark ~/.gtkrc-2.0

/bin/rm -f ~/.config/gtk-3.0/settings.ini
ln -s settings-dark.ini ~/.config/gtk-3.0/settings.ini

/bin/rm -f ~/.config/gtk-4.0/settings.ini
ln -s settings-dark.ini ~/.config/gtk-4.0/settings.ini

echo '[main]
include = ~/.config/foot/colors-dark.ini' > ~/.config/foot/colors.ini

gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

/bin/rm -f ~/.config/waybar/style.css
ln -s style-dark.css ~/.config/waybar/style.css

env -u SESSION_MANAGER lookandfeeltool -a org.manjaro.breath-dark.desktop

sudo ~/bin/set-etc-issue-dark

