#!/bin/zsh

dconf write /theme "'dark'"
dconf write /org/gnome/desktop/interface/gtk-theme "'Orchis-Dark'" 

echo 'gtk-theme-name = "Orchis-Dark"' > ~/.gtkrc-2.0

echo '[Settings]
gtk-theme-name=Orchis-Dark
gtk-icon-theme-name=hicolor
gtk-font-name=Sans 10
gtk-cursor-theme-size=0
gtk-toolbar-style=GTK_TOOLBAR_BOTH
gtk-toolbar-icon-size=GTK_ICON_SIZE_LARGE_TOOLBAR
gtk-button-images=1
gtk-menu-images=1
gtk-enable-event-sounds=1
gtk-enable-input-feedback-sounds=1
gtk-xft-antialias=1
gtk-xft-hinting=1
gtk-xft-hintstyle=hintfull
gtk-application-prefer-dark-theme=1' > ~/.config/gtk-3.0/settings.ini

echo '[Settings]
gtk-theme-name=Orchis-Dark
gtk-application-prefer-dark-theme=1' > ~/.config/gtk-4.0/settings.ini

echo '[main]
include = ~/.config/foot/colors-dark.ini' > ~/.config/foot/colors.ini

gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

cp -f ~/.config/waybar/style-dark.css ~/.config/waybar/style.css

